<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="8" hostname="USHYDAMALBARI1" name="loginTest.LoginTest1" tests="24" failures="4" timestamp="2020-10-25T00:01:59 IST" time="99.417" errors="0">
  <testcase name="NewCustomer" time="3.069" classname="loginTest.LoginTest1"/>
  <system-out/>
  <testcase name="maximize" time="0.000" classname="loginTest.LoginTest1">
    <skipped/>
  </testcase> <!-- maximize -->
  <system-out/>
  <testcase name="NewCustomer" time="5.061" classname="loginTest.LoginTest1"/>
  <system-out/>
  <testcase name="maximize" time="0.223" classname="loginTest.LoginTest1"/>
  <system-out/>
  <testcase name="login" time="10.163" classname="loginTest.LoginTest1"/>
  <system-out/>
  <testcase name="maximize" time="0.000" classname="loginTest.LoginTest1">
    <skipped/>
  </testcase> <!-- maximize -->
  <system-out/>
  <testcase name="login" time="5.354" classname="loginTest.LoginTest1"/>
  <system-out/>
  <testcase name="login" time="10.059" classname="loginTest.LoginTest1">
    <failure type="java.lang.AssertionError" message="Incorrect username and passwordAmit">
      <![CDATA[java.lang.AssertionError: Incorrect username and passwordAmit
at org.testng.Assert.fail(Assert.java:97)
at loginTest.LoginTest1.login(LoginTest1.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- login -->
  <system-out/>
  <testcase name="NewCustomer" time="0.000" classname="loginTest.LoginTest1">
    <skipped/>
  </testcase> <!-- NewCustomer -->
  <system-out/>
  <testcase name="maximize" time="0.477" classname="loginTest.LoginTest1"/>
  <system-out/>
  <testcase name="NewCustomer" time="3.622" classname="loginTest.LoginTest1"/>
  <system-out/>
  <testcase name="maximize" time="0.000" classname="loginTest.LoginTest1">
    <skipped/>
  </testcase> <!-- maximize -->
  <system-out/>
  <testcase name="NewCustomer" time="0.000" classname="loginTest.LoginTest1">
    <skipped/>
  </testcase> <!-- NewCustomer -->
  <system-out/>
  <testcase name="login" time="12.065" classname="loginTest.LoginTest1">
    <failure type="java.lang.AssertionError" message="Incorrect username and passwordSumit">
      <![CDATA[java.lang.AssertionError: Incorrect username and passwordSumit
at org.testng.Assert.fail(Assert.java:97)
at loginTest.LoginTest1.login(LoginTest1.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- login -->
  <system-out/>
  <testcase name="NewCustomer" time="0.000" classname="loginTest.LoginTest1">
    <skipped/>
  </testcase> <!-- NewCustomer -->
  <system-out/>
  <testcase name="login" time="13.929" classname="loginTest.LoginTest1"/>
  <system-out/>
  <testcase name="maximize" time="0.000" classname="loginTest.LoginTest1">
    <skipped/>
  </testcase> <!-- maximize -->
  <system-out/>
  <testcase name="login" time="9.330" classname="loginTest.LoginTest1"/>
  <system-out/>
  <testcase name="maximize" time="0.532" classname="loginTest.LoginTest1"/>
  <system-out/>
  <testcase name="login" time="9.099" classname="loginTest.LoginTest1">
    <failure type="java.lang.AssertionError" message="Incorrect username and passwordAmit">
      <![CDATA[java.lang.AssertionError: Incorrect username and passwordAmit
at org.testng.Assert.fail(Assert.java:97)
at loginTest.LoginTest1.login(LoginTest1.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- login -->
  <system-out/>
  <testcase name="NewCustomer" time="4.540" classname="loginTest.LoginTest1"/>
  <system-out/>
  <testcase name="maximize" time="0.806" classname="loginTest.LoginTest1"/>
  <system-out/>
  <testcase name="login" time="11.088" classname="loginTest.LoginTest1">
    <failure type="java.lang.AssertionError" message="Incorrect username and passwordSumit">
      <![CDATA[java.lang.AssertionError: Incorrect username and passwordSumit
at org.testng.Assert.fail(Assert.java:97)
at loginTest.LoginTest1.login(LoginTest1.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- login -->
  <system-out/>
  <testcase name="NewCustomer" time="0.000" classname="loginTest.LoginTest1">
    <skipped/>
  </testcase> <!-- NewCustomer -->
  <system-out/>
</testsuite> <!-- loginTest.LoginTest1 -->
